// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVALAbQOJfFH6UaO0280nzyTZ1mSq9Ng0',
    appId: '1:540271340306:web:2bab2f63e3914c12d961cb',
    messagingSenderId: '540271340306',
    projectId: 'resumebuilding-5f82f',
    authDomain: 'resumebuilding-5f82f.firebaseapp.com',
    databaseURL: 'https://resumebuilding-5f82f-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilding-5f82f.firebasestorage.app',
    measurementId: 'G-JD3YPMQDQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuzECHcrUeTwfK4K0E4TB5w6K0gU9TSEA',
    appId: '1:540271340306:android:122a33a010be5771d961cb',
    messagingSenderId: '540271340306',
    projectId: 'resumebuilding-5f82f',
    databaseURL: 'https://resumebuilding-5f82f-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilding-5f82f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTSFAlRv1JbHSoavLcJHSVNL3hKQ7ZCMw',
    appId: '1:540271340306:ios:48a329217ec6f54ed961cb',
    messagingSenderId: '540271340306',
    projectId: 'resumebuilding-5f82f',
    databaseURL: 'https://resumebuilding-5f82f-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilding-5f82f.firebasestorage.app',
    iosBundleId: 'com.example.resumeScreening',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTSFAlRv1JbHSoavLcJHSVNL3hKQ7ZCMw',
    appId: '1:540271340306:ios:48a329217ec6f54ed961cb',
    messagingSenderId: '540271340306',
    projectId: 'resumebuilding-5f82f',
    databaseURL: 'https://resumebuilding-5f82f-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilding-5f82f.firebasestorage.app',
    iosBundleId: 'com.example.resumeScreening',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVALAbQOJfFH6UaO0280nzyTZ1mSq9Ng0',
    appId: '1:540271340306:web:ea1f381f50ea03b2d961cb',
    messagingSenderId: '540271340306',
    projectId: 'resumebuilding-5f82f',
    authDomain: 'resumebuilding-5f82f.firebaseapp.com',
    databaseURL: 'https://resumebuilding-5f82f-default-rtdb.firebaseio.com',
    storageBucket: 'resumebuilding-5f82f.firebasestorage.app',
    measurementId: 'G-RWTFR8PTVD',
  );
}
